### ISSUE TITLE
Add Plan and roadmap

### ISSUE THREAD

**Issue by alexbaumgertner** [easy-deep-learning/programming-basics#1]
Глава 1
- [ ] Для чего нужны компьютеры, краткая история вычислительной техники
- [ ] Аналоговые и бинарные вычисления, почему выбран ноль и единица
- [ ] Краткая история современных компьютеров

**Comment by alexbaumgertner** [comment]
How Computers Add Numbers In One Lesson https://www.youtube.com/watch?v=VBDoT8o4q00
https://www.youtube.com/watch?v=5sEp6zyihQQ
